version: '3.8'

services:
  streamlit:
    build:
      context: .
      dockerfile: Dockerfile
    image: data_quality_ecommerce_streamlit
    container_name: data_quality_ecommerce_streamlit
    ports:
      - "8501:8501"
    volumes:
      - ./streamlit.py:/streamlit/streamlit.py
    restart: always